In [2]:
import pandas as pd
import seaborn as sbn
import numpy as np
import datetime as datetime
from matplotlib import pyplot as plt
import re
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon') #get the bloody lexicon

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/JJ/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [2]:
kaggle_df = pd.read_csv('../datasets_2931_4935_data_elonmusk.csv', encoding='latin1')

In [3]:
elon_df = pd.read_csv('./tweet_data/elonmusk.csv')

In [4]:
def standardize_text_old(df, text_field):
    df[text_field] = df[text_field].str.replace(r"http\S+", "")
    df[text_field] = df[text_field].str.replace(r"http", "")
    df[text_field] = df[text_field].str.replace(r"@\S+", "")
    df[text_field] = df[text_field].str.replace(r"RT", "")
    df[text_field] = df[text_field].str.replace(r"[^A-Za-z0-9(),:;!?@\'\`\"\_\n]", " ")
    df[text_field] = df[text_field].str.replace(r"@", "at")
    df[text_field] = df[text_field].str.lower()
    return df
def standardize_text_new(df, text_field):
    df[text_field] = df[text_field].str.replace(r"http\S+", "")
    df[text_field] = df[text_field].str.replace(r"http", "")
    df[text_field] = df[text_field].str.replace(r"@\S+", "")
    df[text_field] = df[text_field].str.replace(r"RT", "")
    df[text_field] = df[text_field].str.replace(r"nan", "")
    df[text_field] = df[text_field].str.replace(r"[^A-Za-z0-9(),:;!?@\'\`\"\_\n]", " ")
    df[text_field] = df[text_field].str.replace(r"@", "at")
    df[text_field] = df[text_field].str.lower()
    df = df[df[text_field].notna()]
    return df

In [5]:
sid = SentimentIntensityAnalyzer() #returns error if no lexicon

In [6]:
kaggle_df.columns

Index(['row ID', 'Tweet', 'Time', 'Retweet from', 'User'], dtype='object')

In [7]:
elon_df.columns

Index(['Unnamed: 0', 'username', 'tweet_id', 'reply_to', 'retweets',
       'favorites', 'hashtags', 'mentions', 'text', 'permalink', 'Time'],
      dtype='object')

Let's try running Vader real fast on the uncleaned headers

In [8]:
for tweet in kaggle_df.head().Tweet:
    ps = sid.polarity_scores(tweet)
    print(ps)

{'neg': 0.0, 'neu': 0.675, 'pos': 0.325, 'compound': 0.8271}
{'neg': 0.0, 'neu': 0.894, 'pos': 0.106, 'compound': 0.3818}
{'neg': 0.0, 'neu': 0.4, 'pos': 0.6, 'compound': 0.4588}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}

In [9]:
for tweet in elon_df.head().text:
    ps = sid.polarity_scores(tweet)
    print(ps)

{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
{'neg': 0.0, 'neu': 0.656, 'pos': 0.344, 'compound': 0.636}

In [10]:
def apply_vader(tweet,category): #gives back the float value of the vader sentiment
    return sid.polarity_scores(tweet)[category]

In [11]:
for tweet in kaggle_df.head().Tweet:
    ps = apply_vader(tweet,'compound')
    print(ps,type(ps))

0.8271 <class 'float'>
0.3818 <class 'float'>
0.4588 <class 'float'>
0.0 <class 'float'>
0.0 <class 'float'>

In [12]:
for tweet in elon_df.head().text:
    ps = apply_vader(tweet,'compound')
    print(ps,type(ps))

0.0 <class 'float'>
0.0 <class 'float'>
0.0 <class 'float'>
0.0 <class 'float'>
0.636 <class 'float'>

Let's do the dumb thing right now

In [13]:
test_df['vader_kaggle_compound'] = kaggle_df.apply(lambda row: apply_vader(kaggle_df['Tweet'],'compound'),axis=1)

AttributeError: 'Series' object has no attribute 'encode'

That didn't work.  Let's use the old data cleaning function

In [17]:
clean_K_df = standardize_text_old(kaggle_df, 'Tweet')

In [18]:
clean_E_df = standardize_text_old(elon_df, 'text')

In [25]:
test_df['vader_kaggle_compound'] = clean_K_df.apply(lambda row: apply_vader(row['Tweet'],'compound'),axis=1)

That worked!

In [26]:
test_df.head()

,row ID,Tweet,Time,Retweet from,User,v_neg,v_neu,v_pos,v_compound,vader_kaggle_compound
0,Row0,"assuming max acceleration of 2 to 3 g's, but ...",2017-09-29 17:39:19,NaN,elonmusk,0.0,0.645,0.355,0.8271,0.8271
1,Row1,bfr is capable of transporting satellites to...,2017-09-29 10:44:54,SpaceX,elonmusk,0.0,0.880,0.120,0.3818,0.3818
2,Row2,yup :),2017-09-29 10:39:57,NaN,elonmusk,0.0,0.250,0.750,0.4588,0.4588
3,Row3,part 2,2017-09-29 09:56:12,NaN,elonmusk,0.0,1.000,0.000,0.0000,0.0000
4,Row4,fly to most places on earth in under 30 mins a...,2017-09-29 09:19:21,NaN,elonmusk,0.0,1.000,0.000,0.0000,0.0000

In [23]:
test_df = clean_K_df
v_cats = ['neg','neu','pos','compound']
for cat in v_cats: #iterates over the 
    test_df['v_'+cat] = clean_K_df.apply(lambda row : apply_vader(row['Tweet'],cat), axis=1)

In [27]:
test_df = clean_E_df
v_cats = ['neg','neu','pos','compound']
for cat in v_cats: #iterates over the 
    test_df['v_'+cat] = clean_E_df.apply(lambda row : apply_vader(row['text'],cat), axis=1)

AttributeError: 'float' object has no attribute 'encode'

That, at least was reproducible.

In [28]:
test_df.index

RangeIndex(start=0, stop=9807, step=1)

In [29]:
for i in range(9806):
    print (i, "text = ",test_df['text'].iloc[i])
    apply_vader(test_df['text'].iloc[i],'compound') #crashes on index 18, which has text of nan

0 text =  nine years later
1 text =  must be due to relativistic aging
2 text =  brought home by same person who placed it there almost a decade ago
3 text =         ,    ,                                                                                        elon
4 text =  congratulations bob   doug on docking   hatch opening on
5 text =  sure
6 text =  probably
7 text =  dragon docks with  in  3 hours
8 text =  dragonship endeavor
9 text =  5 mins to t 0
10 text =  falcon dragon are designed to withstand multiple lightning strikes, but we don t think it would be wise to take this risk
11 text =  proceeding with countdown today, weather cancellation risk  50
12 text =  yes
13 text =  worth noting that, as of jan 1, tesla buyers no longer received any federal tax credit  model 3 led despite this disadvantage
14 text =  we slowed down a bit to allow supercharger v3 production to get going, but now will speed up!
15 text =  more superchargers coming soon!
16 text =  he is great
17 text =  human kind
18 text =  nan

AttributeError: 'float' object has no attribute 'encode'

In [48]:
elon_df = elon_df[elon_df['text'].notna()].reset_index()

In [49]:
elon_df.head(20)

,level_0,index,Unnamed: 0,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time
0,0,0,0,elonmusk,1267180654896254976,SpaceX,22581,250519,[],NaN,Nine years later,https://twitter.com/elonmusk/status/1267180654...,2020-05-31 19:46:25+00:00
1,1,1,1,elonmusk,1267160409498357764,NASASpaceflight,81,2494,[],NaN,Must be due to relativistic aging,https://twitter.com/elonmusk/status/1267160409...,2020-05-31 18:25:58+00:00
2,2,2,2,elonmusk,1267157474886455296,NASASpaceflight,708,14436,[],NaN,Brought home by same person who placed it ther...,https://twitter.com/elonmusk/status/1267157474...,2020-05-31 18:14:19+00:00
3,3,3,3,elonmusk,1267156817295085575,Rogozin,1209,7558,[],NaN,"Спасибо, сэр, ха-ха. Мы рассчитываем на взаимо...",https://twitter.com/elonmusk/status/1267156817...,2020-05-31 18:11:42+00:00
4,4,4,4,elonmusk,1267146619562201090,SpaceX,5576,67423,[],@Space_Station,Congratulations Bob & Doug on docking & hatch ...,https://twitter.com/elonmusk/status/1267146619...,2020-05-31 17:31:11+00:00
5,5,5,5,elonmusk,1267057495773675521,TeslaGong,81,3948,[],NaN,Sure,https://twitter.com/elonmusk/status/1267057495...,2020-05-31 11:37:02+00:00
6,6,6,6,elonmusk,1267056905601638404,TeslaTested,1650,84762,[],NaN,Probably,https://twitter.com/elonmusk/status/1267056905...,2020-05-31 11:34:41+00:00
7,7,7,7,elonmusk,1267056312497721344,SpaceX,16259,149590,[],@Space_Station,Dragon docks with @Space_Station in ~3 hours,https://twitter.com/elonmusk/status/1267056312...,2020-05-31 11:32:20+00:00
8,8,8,8,elonmusk,1266890648587776003,NASA,4042,64610,[],NaN,Dragonship Endeavor,https://twitter.com/elonmusk/status/1266890648...,2020-05-31 00:34:02+00:00
9,9,9,9,elonmusk,1266811094527508481,NaN,54238,862612,[],NaN,5 mins to T-0,https://twitter.com/elonmusk/status/1266811094...,2020-05-30 19:17:55+00:00
10,10,10,10,elonmusk,1266695491879911424,engineers_feed,2514,61568,[],NaN,Falcon/Dragon are designed to withstand multip...,https://twitter.com/elonmusk/status/1266695491...,2020-05-30 11:38:33+00:00
11,11,11,11,elonmusk,1266694593480929282,Commercial_Crew,2632,26203,[],NaN,"Proceeding with countdown today, weather cance...",https://twitter.com/elonmusk/status/1266694593...,2020-05-30 11:34:59+00:00
12,12,12,12,elonmusk,1266678248072757248,fermatslibrary,157,4950,[],NaN,Yes,https://twitter.com/elonmusk/status/1266678248...,2020-05-30 10:30:02+00:00
13,13,13,13,elonmusk,1266436499341545472,cleantechnica,477,11566,[],NaN,"Worth noting that, as of Jan 1, Tesla buyers n...",https://twitter.com/elonmusk/status/1266436499...,2020-05-29 18:29:25+00:00
14,14,14,14,elonmusk,1266194688077422609,Erdayastronaut,159,4100,[],NaN,We slowed down a bit to allow Supercharger V3 ...,https://twitter.com/elonmusk/status/1266194688...,2020-05-29 02:28:33+00:00
15,15,15,15,elonmusk,1266193280749965315,vincent13031925,811,34494,[],NaN,More Superchargers coming soon!,https://twitter.com/elonmusk/status/1266193280...,2020-05-29 02:22:57+00:00
16,16,16,16,elonmusk,1265792824722829313,SciGuySpace,135,6128,[],NaN,He is great,https://twitter.com/elonmusk/status/1265792824...,2020-05-27 23:51:41+00:00
17,17,17,17,elonmusk,1265759902242308096,SpaceX,1054,27451,[],NaN,human kind,https://twitter.com/elonmusk/status/1265759902...,2020-05-27 21:40:52+00:00
18,18,19,19,elonmusk,1265488797254516738,NaN,54529,498073,[],NaN,Sunset,https://twitter.com/elonmusk/status/1265488797...,2020-05-27 03:43:35+00:00
19,19,20,20,elonmusk,1265484748811653121,SciGuySpace,263,5272,[],NaN,"Yeah, Atlantic weather review tomorrow morning...",https://twitter.com/elonmusk/status/1265484748...,2020-05-27 03:27:30+00:00

In [52]:
test_df = standardize_text_new(elon_df, 'text')
v_cats = ['neg','neu','pos','compound']
for cat in v_cats: #iterates over the 
    test_df['v_'+cat] = test_df.apply(lambda row : apply_vader(row['text'],cat), axis=1)

In [53]:
test_df.head()

,level_0,index,Unnamed: 0,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time,v_neg,v_neu,v_pos,v_compound
0,0,0,0,elonmusk,1267180654896254976,SpaceX,22581,250519,[],NaN,nine years later,https://twitter.com/elonmusk/status/1267180654...,2020-05-31 19:46:25+00:00,0.0,1.000,0.000,0.0000
1,1,1,1,elonmusk,1267160409498357764,NASASpaceflight,81,2494,[],NaN,must be due to relativistic aging,https://twitter.com/elonmusk/status/1267160409...,2020-05-31 18:25:58+00:00,0.0,1.000,0.000,0.0000
2,2,2,2,elonmusk,1267157474886455296,NASASpaceflight,708,14436,[],NaN,brought home by same person who placed it ther...,https://twitter.com/elonmusk/status/1267157474...,2020-05-31 18:14:19+00:00,0.0,1.000,0.000,0.0000
3,3,3,3,elonmusk,1267156817295085575,Rogozin,1209,7558,[],NaN,", , ...",https://twitter.com/elonmusk/status/1267156817...,2020-05-31 18:11:42+00:00,0.0,1.000,0.000,0.0000
4,4,4,4,elonmusk,1267146619562201090,SpaceX,5576,67423,[],@Space_Station,congratulations bob doug on docking hatch ...,https://twitter.com/elonmusk/status/1267146619...,2020-05-31 17:31:11+00:00,0.0,0.642,0.358,0.5994

In [60]:
test_df['Time'] = pd.to_datetime(test_df['Time'])
test_df['delta_Time'] = abs(pd.to_timedelta((test_df['Time']-test_df['Time']\
                                                     .shift(-1)).fillna(0.)).astype('timedelta64[s]'))\
                                                     .replace(0.,60.)
test_df.head()

,level_0,index,Unnamed: 0,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time,v_neg,v_neu,v_pos,v_compound,delta_Time
0,0,0,0,elonmusk,1267180654896254976,SpaceX,22581,250519,[],NaN,nine years later,https://twitter.com/elonmusk/status/1267180654...,2020-05-31 19:46:25+00:00,0.0,1.000,0.000,0.0000,4827.0
1,1,1,1,elonmusk,1267160409498357764,NASASpaceflight,81,2494,[],NaN,must be due to relativistic aging,https://twitter.com/elonmusk/status/1267160409...,2020-05-31 18:25:58+00:00,0.0,1.000,0.000,0.0000,699.0
2,2,2,2,elonmusk,1267157474886455296,NASASpaceflight,708,14436,[],NaN,brought home by same person who placed it ther...,https://twitter.com/elonmusk/status/1267157474...,2020-05-31 18:14:19+00:00,0.0,1.000,0.000,0.0000,157.0
3,3,3,3,elonmusk,1267156817295085575,Rogozin,1209,7558,[],NaN,", , ...",https://twitter.com/elonmusk/status/1267156817...,2020-05-31 18:11:42+00:00,0.0,1.000,0.000,0.0000,2431.0
4,4,4,4,elonmusk,1267146619562201090,SpaceX,5576,67423,[],@Space_Station,congratulations bob doug on docking hatch ...,https://twitter.com/elonmusk/status/1267146619...,2020-05-31 17:31:11+00:00,0.0,0.642,0.358,0.5994,21249.0

In [93]:
#test_df = test_df.drop(['level_0','index','Unnamed: 0'],axis='columns').sort_values(by='Time')
test_df = test_df.reset_index().drop('index',axis='columns')
test_df.head()

,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time,v_neg,v_neu,v_pos,v_compound,delta_Time
0,elonmusk,15434727182,NaN,125,469,[],NaN,"please ignore prior tweets, as that was someon...",https://twitter.com/elonmusk/status/15434727182,2010-06-04 18:31:57+00:00,0.113,0.586,0.302,0.4939,60.0
1,elonmusk,142179928203460608,NaN,18,166,[],NaN,went to iceland on sat to ride bumper cars on ...,https://twitter.com/elonmusk/status/1421799282...,2011-12-01 09:55:11+00:00,0.067,0.608,0.325,0.8588,47056994.0
2,elonmusk,142188458125963264,NaN,8,23,[],NaN,i made the volume on the model s go to 11 no...,https://twitter.com/elonmusk/status/1421884581...,2011-12-01 10:29:04+00:00,0.000,1.000,0.000,0.0000,2033.0
3,elonmusk,142880871391838208,NaN,25,29,[],NaN,"great voltaire quote, arguably better than twa...",https://twitter.com/elonmusk/status/1428808713...,2011-12-03 08:20:28+00:00,0.186,0.505,0.309,0.5994,165084.0
4,elonmusk,142881284019060736,NaN,4,7,[],NaN,that was a total non sequitur btw,https://twitter.com/elonmusk/status/1428812840...,2011-12-03 08:22:07+00:00,0.000,1.000,0.000,0.0000,99.0

In [95]:
test_df['hour'] = test_df['Time'].dt.hour
test_df.head()

,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time,v_neg,v_neu,v_pos,v_compound,delta_Time,hour
0,elonmusk,15434727182,NaN,125,469,[],NaN,"please ignore prior tweets, as that was someon...",https://twitter.com/elonmusk/status/15434727182,2010-06-04 18:31:57+00:00,0.113,0.586,0.302,0.4939,60.0,18
1,elonmusk,142179928203460608,NaN,18,166,[],NaN,went to iceland on sat to ride bumper cars on ...,https://twitter.com/elonmusk/status/1421799282...,2011-12-01 09:55:11+00:00,0.067,0.608,0.325,0.8588,47056994.0,9
2,elonmusk,142188458125963264,NaN,8,23,[],NaN,i made the volume on the model s go to 11 no...,https://twitter.com/elonmusk/status/1421884581...,2011-12-01 10:29:04+00:00,0.000,1.000,0.000,0.0000,2033.0,10
3,elonmusk,142880871391838208,NaN,25,29,[],NaN,"great voltaire quote, arguably better than twa...",https://twitter.com/elonmusk/status/1428808713...,2011-12-03 08:20:28+00:00,0.186,0.505,0.309,0.5994,165084.0,8
4,elonmusk,142881284019060736,NaN,4,7,[],NaN,that was a total non sequitur btw,https://twitter.com/elonmusk/status/1428812840...,2011-12-03 08:22:07+00:00,0.000,1.000,0.000,0.0000,99.0,8

In [98]:
len(test_df['hour'].index)

9708

In [99]:
test_df['v_compound'].mean()

0.18496270086526576

In [100]:
test_df['v_compound'].median()

0.0

In [102]:
test_df.drop('tweet_id',axis='columns')
['username','reply_to','retweets','favorites','hashtags','mentions','text','permalink','Time']

,username,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time,v_neg,v_neu,v_pos,v_compound,delta_Time,hour
0,elonmusk,NaN,125,469,[],NaN,"please ignore prior tweets, as that was someon...",https://twitter.com/elonmusk/status/15434727182,2010-06-04 18:31:57+00:00,0.113,0.586,0.302,0.4939,60.0,18
1,elonmusk,NaN,18,166,[],NaN,went to iceland on sat to ride bumper cars on ...,https://twitter.com/elonmusk/status/1421799282...,2011-12-01 09:55:11+00:00,0.067,0.608,0.325,0.8588,47056994.0,9
2,elonmusk,NaN,8,23,[],NaN,i made the volume on the model s go to 11 no...,https://twitter.com/elonmusk/status/1421884581...,2011-12-01 10:29:04+00:00,0.000,1.000,0.000,0.0000,2033.0,10
3,elonmusk,NaN,25,29,[],NaN,"great voltaire quote, arguably better than twa...",https://twitter.com/elonmusk/status/1428808713...,2011-12-03 08:20:28+00:00,0.186,0.505,0.309,0.5994,165084.0,8
4,elonmusk,NaN,4,7,[],NaN,that was a total non sequitur btw,https://twitter.com/elonmusk/status/1428812840...,2011-12-03 08:22:07+00:00,0.000,1.000,0.000,0.0000,99.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9703,elonmusk,SpaceX,5576,67423,[],@Space_Station,congratulations bob doug on docking hatch ...,https://twitter.com/elonmusk/status/1267146619...,2020-05-31 17:31:11+00:00,0.000,0.642,0.358,0.5994,21249.0,17
9704,elonmusk,Rogozin,1209,7558,[],NaN,", , ...",https://twitter.com/elonmusk/status/1267156817...,2020-05-31 18:11:42+00:00,0.000,1.000,0.000,0.0000,2431.0,18
9705,elonmusk,NASASpaceflight,708,14436,[],NaN,brought home by same person who placed it ther...,https://twitter.com/elonmusk/status/1267157474...,2020-05-31 18:14:19+00:00,0.000,1.000,0.000,0.0000,157.0,18
9706,elonmusk,NASASpaceflight,81,2494,[],NaN,must be due to relativistic aging,https://twitter.com/elonmusk/status/1267160409...,2020-05-31 18:25:58+00:00,0.000,1.000,0.000,0.0000,699.0,18
9707,elonmusk,SpaceX,22581,250519,[],NaN,nine years later,https://twitter.com/elonmusk/status/1267180654...,2020-05-31 19:46:25+00:00,0.000,1.000,0.000,0.0000,4827.0,19

In [107]:
test_df[['v_compound','delta_Time']].min().abs()

v_compound    0.9638
delta_Time    1.0000
dtype: float64

In [111]:
test_df[['v_compound','delta_Time']].max().abs()

v_compound    9.787000e-01
delta_Time    4.705699e+07
dtype: float64

In [110]:
huh = ['v_compound','delta_Time']

In [114]:
for x in huh:
    print(max(abs(test_df[x].min()),test_df[x].max()))

0.9787
47056994.0

In [16]:
def reload_tweet_data(username="elonmusk"):
   #note we'll have to do a .drop and set the 'Time' column to the proper values every time
    df = pd.read_csv('./tweet_data/'+username+'.csv').drop(['Unnamed: 0'],axis='columns')
    #order by earliest first
    df['Time'] = pd.to_datetime(df['Time'])#.sort_values(by='Time',ascending=True)
    return df.sort_values(by='Time',ascending=True).reset_index().drop('index',axis='columns')
elon_df = reload_tweet_data()

In [142]:
elon_df[elon_df['hashtags']!='[]']

,username,tweet_id,reply_to,retweets,favorites,hashtags,mentions,text,permalink,Time
40,elonmusk,153099684280410112,NaN,10,10,['#whatcouldpossiblygowrong'],NaN,hacked my tesla charge connector on a small is...,https://twitter.com/elonmusk/status/1530996842...,2011-12-31 13:06:23+00:00
99,elonmusk,173476402748854274,NaN,11,4,['#PlutoStamp'],@NASA,supporting the drive to get a plutostamp for ...,https://twitter.com/elonmusk/status/1734764027...,2012-02-25 18:36:12+00:00
113,elonmusk,182211270479577088,NaN,39,4,['#antarctica'],@Polar_Broadband,support as they try to save a good satellite ...,https://twitter.com/elonmusk/status/1822112704...,2012-03-20 21:05:26+00:00
141,elonmusk,198113448628981760,WHester,11,34,['#APSpaceChat'],@WHester,"ignition by john clarke, huzel wang book on ...",https://twitter.com/elonmusk/status/1981134486...,2012-05-03 18:15:01+00:00
142,elonmusk,198115378759610368,Weaverwerx,99,48,"['#OccupyMars', '#APSpaceChat']",@Weaverwerx,definitely long term goal of spacex making li...,https://twitter.com/elonmusk/status/1981153787...,2012-05-03 18:22:41+00:00
143,elonmusk,198116544855801856,love_to_dream,178,46,['#APSpaceChat'],@love_to_dream,for humanity to have an exciting inspiring f...,https://twitter.com/elonmusk/status/1981165448...,2012-05-03 18:27:19+00:00
158,elonmusk,204837633766076418,NaN,113,17,['#dragonlaunch'],NaN,t minus 10 minutes entering terminal count...,https://twitter.com/elonmusk/status/2048376337...,2012-05-22 07:34:32+00:00
159,elonmusk,204839936464134144,NaN,105,26,['#DragonLaunch'],NaN,t minus 60 seconds terminal autosequence init...,https://twitter.com/elonmusk/status/2048399364...,2012-05-22 07:43:41+00:00
163,elonmusk,204882126884188160,NaN,455,114,['#DragonLaunch'],NaN,dragon spaceship opens the navigation pod bay ...,https://twitter.com/elonmusk/status/2048821268...,2012-05-22 10:31:20+00:00
164,elonmusk,204883910654570496,NaN,121,36,['#DragonLaunch'],NaN,navigation bay pointing to deep space and star...,https://twitter.com/elonmusk/status/2048839106...,2012-05-22 10:38:25+00:00
165,elonmusk,204911319260987392,NaN,477,176,['#dragonlaunch'],NaN,launch video of falcon 9 from cape canaveral t...,https://twitter.com/elonmusk/status/2049113192...,2012-05-22 12:27:20+00:00
166,elonmusk,205314559542693888,NaN,207,27,['#dragonlaunch'],NaN,dragon fly by of space station planned for 12:...,https://twitter.com/elonmusk/status/2053145595...,2012-05-23 15:09:40+00:00
168,elonmusk,205544630199132160,NaN,226,47,['#Dragon'],NaN,about 110 miles away and the spacecraft is now...,https://twitter.com/elonmusk/status/2055446301...,2012-05-24 06:23:53+00:00
170,elonmusk,205723666590334976,NaN,125,99,['#GrasshopperProject'],NaN,dragon flies over the spacex grasshopperproje...,https://twitter.com/elonmusk/status/2057236665...,2012-05-24 18:15:19+00:00
172,elonmusk,206118185173389312,NaN,149,89,['#Dragon'],NaN,space station tracking spaceship docking appro...,https://twitter.com/elonmusk/status/2061181851...,2012-05-25 20:23:00+00:00
173,elonmusk,208201556271697922,NaN,176,25,['#Dragon'],NaN,spaceship has departed from the international ...,https://twitter.com/elonmusk/status/2082015562...,2012-05-31 14:21:33+00:00
174,elonmusk,208204036258803712,NaN,134,35,['#Dragon'],NaN,thrusters will also fire during reentry to adj...,https://twitter.com/elonmusk/status/2082040362...,2012-05-31 14:31:25+00:00
175,elonmusk,208223378782420993,NaN,370,46,['#Dragon'],NaN,splashdown successful!! sending fast boat to d...,https://twitter.com/elonmusk/status/2082233787...,2012-05-31 15:48:16+00:00
197,elonmusk,223430899004485634,n23mc,24,15,['#OccupyMars'],@n23mc,i think we will see people on mars in less th...,https://twitter.com/elonmusk/status/2234308990...,2012-07-12 14:57:32+00:00
276,elonmusk,271652314744487936,NaN,67,14,['#Climate'],@newscientist,on the plus side climate change has a sil...,https://twitter.com/elonmusk/status/2716523147...,2012-11-22 16:32:13+00:00
286,elonmusk,275346615634624514,NaN,692,151,['#AwesomeXmasGifts'],NaN,uranium ore now available on amazon! so much m...,https://twitter.com/elonmusk/status/2753466156...,2012-12-02 21:12:03+00:00
298,elonmusk,278953918338326528,NaN,123,63,['#Zeitgeist2012'],NaN,cool video recap of the big events of the year...,https://twitter.com/elonmusk/status/2789539183...,2012-12-12 20:06:11+00:00
324,elonmusk,298266134128496641,NaN,27,31,['#SB47'],@49ers,great spirit here in the superdome awesome ra...,https://twitter.com/elonmusk/status/2982661341...,2013-02-04 03:06:02+00:00
364,elonmusk,307958110474104832,NaN,328,149,['#Dragon'],@NASA,just received dragon docking clearance from ...,https://twitter.com/elonmusk/status/3079581104...,2013-03-02 20:58:29+00:00
368,elonmusk,310036546327834625,NaN,135,80,['#SXSW'],NaN,arrived austin talking with tx house about cr...,https://twitter.com/elonmusk/status/3100365463...,2013-03-08 14:37:27+00:00
375,elonmusk,310478997077258241,NaN,136,49,['#SXSW'],NaN,will show johnny cash hover slam rocket video ...,https://twitter.com/elonmusk/status/3104789970...,2013-03-09 19:55:35+00:00
417,elonmusk,319121972212690945,NaN,149,126,['#hhgttg'],NaN,certainly true that many people believe that t...,https://twitter.com/elonmusk/status/3191219722...,2013-04-02 16:19:41+00:00
418,elonmusk,319144496187187202,NaN,69,47,['#TeslaTX'],NaN,am headed to tx next week to thank people pers...,https://twitter.com/elonmusk/status/3191444961...,2013-04-02 17:49:11+00:00
637,elonmusk,361316902804529153,NaN,426,279,['#KatieWoodencloak'],NaN,one of the first tesla supercharger stations i...,https://twitter.com/elonmusk/status/3613169028...,2013-07-28 02:47:17+00:00
750,elonmusk,434129460179128320,NaN,164,208,['#Yutu'],NaN,welcome back jade rabbit! yutu,https://twitter.com/elonmusk/status/4341294601...,2014-02-14 00:58:23+00:00
3241,elonmusk,960915618865274880,NaN,23054,81495,"['#FalconHeavy', '#SpaceX']",NaN,flight profile falconheavy spacex,https://twitter.com/elonmusk/status/9609156188...,2018-02-06 16:38:31+00:00
3242,elonmusk,960921700153135104,NaN,3506,31952,['#FalconHeavy'],NaN,upper atmosphere winds currently 20 above max...,https://twitter.com/elonmusk/status/9609217001...,2018-02-06 17:02:41+00:00
3243,elonmusk,960949244982018049,NaN,9595,56835,['#FalconHeavy'],NaN,launch auto sequence initiated (aka the holy m...,https://twitter.com/elonmusk/status/9609492449...,2018-02-06 18:52:08+00:00
3244,elonmusk,960975644644593664,NaN,7940,41038,['#FalconHeavy'],NaN,camera views from inside the payload fairing ...,https://twitter.com/elonmusk/status/9609756446...,2018-02-06 20:37:02+00:00
3879,elonmusk,1002237545273483264,paulmasonnews,387,5049,['#Pravduh'],NaN,pravduh,https://twitter.com/elonmusk/status/1002237545...,2018-05-31 17:17:06+00:00
3943,elonmusk,1005564275656568832,NaN,8802,45802,['#ThrowFlamesResponsibly'],NaN,terms conditions for not a flamethrower pl...,https://twitter.com/elonmusk/status/1005564275...,2018-06-09 21:36:20+00:00
4150,elonmusk,1010431046460923905,NaN,306,5235,['#donotpanic'],NaN,donotpanic,https://twitter.com/elonmusk/status/1010431046...,2018-06-23 07:55:09+00:00
4722,elonmusk,1041555319166447616,NaN,15252,83580,['#OccupyMars'],NaN,occupymars,https://twitter.com/elonmusk/status/1041555319...,2018-09-17 05:11:53+00:00
5512,elonmusk,1082180642937491456,NaN,33665,312123,['#NewProfilePic'],NaN,newprofilepic,https://twitter.com/elonmusk/status/1082180642...,2019-01-07 07:42:25+00:00
6818,elonmusk,1141132845202599937,nichegamer,147,6235,['#moneygang'],NaN,"actually, i stole it from my secret meme deale...",https://twitter.com/elonmusk/status/1141132845...,2019-06-18 23:57:26+00:00
7761,elonmusk,1179957355628253185,SciGuySpace,3333,31908,['#Armageddon69'],@NASA,excited about launching asteroid defense miss...,https://twitter.com/elonmusk/status/1179957355...,2019-10-04 03:12:10+00:00
8662,elonmusk,1226132778967687170,SachaBaronCohen,8248,60748,['#DeleteFacebook'],NaN,deletefacebook it s lame,https://twitter.com/elonmusk/status/1226132778...,2020-02-08 13:16:49+00:00
9245,elonmusk,1251335445977403392,flcnhvy,316,2280,['#CancelNewsNetwork'],NaN,cancelnewsnetwork,https://twitter.com/elonmusk/status/1251335445...,2020-04-18 02:23:13+00:00

In [14]:
import nltk
import pandas as pd
import numpy as np
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.tokenize import RegexpTokenizer
import re
nltk.download('vader_lexicon') #get the bloody lexicon
sid = SentimentIntensityAnalyzer() #returns error if no lexicon

def standardize_text(df, text_field):
    df[text_field] = df[text_field].str.replace(r"http\S+", "")
    df[text_field] = df[text_field].str.replace(r"http", "")
    df[text_field] = df[text_field].str.replace(r"@\S+", "")
    df[text_field] = df[text_field].str.replace(r"RT", "")
    df[text_field] = df[text_field].str.replace(r"[^A-Za-z0-9(),:;!?@\'\`\"\_\n]", " ")
    df[text_field] = df[text_field].str.replace(r"@", "at")
    df[text_field] = df[text_field].str.lower()
    df = df[df[text_field].notna()]
    return df

def apply_vader(tweet,category): #gives back the float value of the vader sentiment
    return sid.polarity_scores(tweet)[category]

def tokenize_hashtags(df): #tokenize hashtags, using one hot encoding
    df['hashtags_token'] = 0. #initialize all to zero
    df['hashtags_token'].loc[df['hashtags'] != '[]'] = 1. #any field with a hashtag set to 1.
    return df

def tokenize_mentions(df): #tokenize mentions, using one hot encoding
    df['mentions_token'] = 0. #initialize all to zero
    df['mentions_token'].loc[df['mentions'].notna()] = 1. #any field with a mention set to 1.
    return df

def tokenize_reply_to(df): #tokenize mentions, using one hot encoding
    df['reply_to_token'] = 0. #initialize all to zero
    df['reply_to_token'].loc[df['reply_to'].notna()] = 1. #any field with a reply_to set to 1.
    return df

def convert_hashtag(input_txt):
    if input_txt == '[]': #return empty string if no hashtag
        return ""
    input_list = input_txt.strip("['']").split("', '") #strips out useless characters
    txt_list = re.findall('[A-Z][^A-Z]*', " ".join(input_list)) #splits hastags into words on Captial letters
    return " ".join(txt_list)

def tweet_word_count(df):
    tokenizer = RegexpTokenizer(r'\w+') #split on words
    df["tokens"] = df["tweet"].apply(tokenizer.tokenize) #returns list of individual words
    df['tweet_length'] = df.apply(lambda row : len(row['tokens']), axis=1) #creates tweet length column
    df = df.drop(['tokens'],axis='columns') #drops the temporary column
    return df   

def integral_history(df,category,length):
    #the depth back in tweet history
    result = df[category]
    
    
def construct_features(tweets):
    """Constructs features from Elon's tweet data"""
    # Clean the text of the tweets
    tweets = standardize_text(tweets,"text")
    # Tokenize the hashtags
    tweets = tokenize_hashtags(tweets)
    # Tokenize the mentions
    tweets = tokenize_mentions(tweets)
    # Tokenize the reply_to
    tweets = tokenize_reply_to(tweets)
    # Clean the text of the hastags
    tweets["hashtags"] = tweets.apply(lambda row: convert_hashtag(row['hashtags']),axis=1)
    # Prepare to apply vader to the tweets
    vader_categories = ['neg','neu','pos','compound']
    # Apply vader to the tweets
    for cat in vader_categories: #iterates over the categories
        #creates new feature each iteration
        tweets['text_'+cat] = tweets.apply(lambda row : apply_vader(row['text'],cat), axis=1)
    # Apply vader to the hashtags
    for cat in vader_categories: #iterates over the categories
        #creates new feature each iteration
        tweets['hashtags_'+cat] = tweets.apply(lambda row : apply_vader(row['hashtags'],cat), axis=1)
    #Do some temporal processing
    #Hour of the day
    tweets['hour'] = tweets['Time'].dt.hour
    #Time between tweets in seconds
    tweets['delta_time'] = abs(pd.to_timedelta((tweets['Time']-tweets['Time']\
                                                     .shift()).fillna(6000.)).astype('timedelta64[s]'))\
                                                     .replace(0.,6000.)
    tweets['log10_delta_time'] = np.log10(abs(pd.to_timedelta((tweets['Time']-tweets['Time']\
                                                     .shift()).fillna(60.)).astype('timedelta64[s]')\
                                                     .replace(0.,6000.)))
    #Make some rate of sentiment change features
    tweets['dcompound_dTime'] = (tweets['text_compound']-tweets['text_compound']
                                           .shift()).fillna(0.)/(tweets['delta_time']) #change per second
    tweets['dcompound_dTweet'] = (tweets['text_compound']-tweets['text_compound']
                                            .shift()).fillna(0.) #change per tweet
    #Make some integral sentiment change features
    tweets['integral_compound_5'] = tweets['text_compound'].rolling(min_periods=1, window=5).sum()
    tweets['integral_compound_10'] = tweets['text_compound'].rolling(min_periods=1, window=10).sum()
    #Make a difference sentiment features
    tweets['delta_compound_mean'] = tweets['text_compound'] - tweets['text_compound'].mean()
    tweets['delta_compound_median'] = tweets['text_compound'] - tweets['text_compound'].median()
    #All done for now
    return tweets

def strip_down_to_features_and_rescale(df):
    #drop improperly formatted data
    df = df.drop(['username','reply_to','retweets',
                  'tweet_id','favorites','hashtags','mentions',
                  'text','permalink','Time'],axis='columns')
    # These features are on a 0 to 1 scale
    zero_to_one = ['hour','delta_time','log10_delta_time']
    # These features are on a -1 to 1 scale
    negone_to_one = ['dcompound_dTime','dcompound_dTweet','integral_compound_5',
                    'integral_compound_10','delta_compound_mean','delta_compound_median']
    # shrink the scale for the zero_to_one features
    zero_to_one_scale = df[zero_to_one].max()
    df[zero_to_one] /= df[zero_to_one].max()
    # shrink the scale for the -1 to 1 ranges
    # need to preserve true zero, however, so no shifting the mean
    negone_to_one_scale = [] #list to hold the rescaling
    for x in negone_to_one:
        # this won't fill the entire range -1 to 1, but it preserves true 0
        df[x] /= max(abs(df[x].min()),df[x].max())
        negone_to_one_scale += [max(abs(df[x].min()),df[x].max())]
    return df,zero_to_one_scale,negone_to_one_scale

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/JJ/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [17]:
test_df = construct_features(elon_df)

<ipython-input-14-5c7a031bc419>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hashtags_token'] = 0. #initialize all to zero
<ipython-input-14-5c7a031bc419>:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hashtags_token'].loc[df['hashtags'] != '[]'] = 1. #any field with a hashtag set to 1.
<ipython-input-14-5c7a031bc419>:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mentions_token'] = 0. #initialize all to zero
<ipython-input-14-5c7a031bc419>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mentions_token'].loc[df['mentions'].notna()] = 1. #any field with a mention set to 1.
<ipython-input-14-5c7a031bc419>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reply_to_token'] = 0. #initialize all to zero
<ipython-input-14-5c7a031bc419>:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reply_to_token'].loc[df['reply_to'].notna()] = 1. #any field with a reply_to set to 1.
<ipython-input-14-5c7a031bc419>:69: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets["hashtags"] = tweets.apply(lambda row: convert_hashtag(row['hashtags']),axis=1)
<ipython-input-14-5c7a031bc419>:75: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['text_'+cat] = tweets.apply(lambda row : apply_vader(row['text'],cat), axis=1)
<ipython-input-14-5c7a031bc419>:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['hashtags_'+cat] = tweets.apply(lambda row : apply_vader(row['hashtags'],cat), axis=1)
<ipython-input-14-5c7a031bc419>:82: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['hour'] = tweets['Time'].dt.hour
<ipython-input-14-5c7a031bc419>:84: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['delta_time'] = abs(pd.to_timedelta((tweets['Time']-tweets['Time']\
<ipython-input-14-5c7a031bc419>:87: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['log10_delta_time'] = np.log10(abs(pd.to_timedelta((tweets['Time']-tweets['Time']\
<ipython-input-14-5c7a031bc419>:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['dcompound_dTime'] = (tweets['text_compound']-tweets['text_compound']
<ipython-input-14-5c7a031bc419>:93: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['dcompound_dTweet'] = (tweets['text_compound']-tweets['text_compound']
<ipython-input-14-5c7a031bc419>:96: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['integral_compound_5'] = tweets['text_compound'].rolling(min_periods=1, window=5).sum()
<ipython-input-14-5c7a031bc419>:97: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['integral_compound_10'] = tweets['text_compound'].rolling(min_periods=1, window=10).sum()
<ipython-input-14-5c7a031bc419>:99: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['delta_compound_mean'] = tweets['text_compound'] - tweets['text_compound'].mean()
<ipython-input-14-5c7a031bc419>:100: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tweets['delta_compound_median'] = tweets['text_compound'] - tweets['text_compound'].median()

In [19]:
test_df.to_csv('./tweet_data/unscaled_tweet_features.csv')

In [18]:
check_me = test_df[elon_df['hashtags']!='[]']
check_me['hashtags']

<ipython-input-18-aadefb412182>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  check_me = test_df[elon_df['hashtags']!='[]']

40
99                       Pluto Stamp
113
141                   A P Space Chat
142     Occupy Mars # A P Space Chat
143                   A P Space Chat
158
159                    Dragon Launch
163                    Dragon Launch
164                    Dragon Launch
165
166
168                           Dragon
170              Grasshopper Project
172                           Dragon
173                           Dragon
174                           Dragon
175                           Dragon
197                      Occupy Mars
276                          Climate
286               Awesome Xmas Gifts
298                    Zeitgeist2012
324                            S B47
364                           Dragon
368                          S X S W
375                          S X S W
417
418                        Tesla T X
637                Katie Woodencloak
750                             Yutu
3241          Falcon Heavy # Space X
3242                    Falcon Heavy
3243                    Falcon Heavy
3244                    Falcon Heavy
3879                         Pravduh
3943        Throw Flames Responsibly
4150
4722                     Occupy Mars
5512                 New Profile Pic
6818
7761                    Armageddon69
8662                 Delete Facebook
9245             Cancel News Network
Name: hashtags, dtype: object

In [182]:
check_me = test_df[test_df['hashtags_token'] > 0.]
check_me[['hashtags_neg','hashtags_neu','hashtags_pos','hashtags_compound']].tail()

      hashtags_neg  hashtags_neu  hashtags_pos  hashtags_compound
5512           0.0           1.0           0.0               0.00
6818           0.0           0.0           0.0               0.00
7761           0.0           1.0           0.0               0.00
8662           0.0           1.0           0.0               0.00
9245           0.5           0.5           0.0              -0.25

In [198]:
rescale_df,scale1,scale2 = strip_down_to_features_and_rescale(test_df)

In [199]:
rescale_df.max()

hashtags_token           1.000000
mentions_token           1.000000
reply_to_token           1.000000
text_neg                 1.000000
text_neu                 1.000000
text_pos                 1.000000
text_compound            0.978700
hashtags_neg             0.500000
hashtags_neu             1.000000
hashtags_pos             0.672000
hashtags_compound        0.624900
hour                     1.000000
delta_time               1.000000
log10_delta_time         1.000000
dcompound_dTime          1.000000
dcompound_dTweet         1.000000
integral_compound_5      1.000000
integral_compound_10     1.000000
delta_compound_mean      0.691017
delta_compound_median    1.000000
dtype: float64

In [201]:
rescale_df.min()

hashtags_token           0.000000e+00
mentions_token           0.000000e+00
reply_to_token           0.000000e+00
text_neg                 0.000000e+00
text_neu                 0.000000e+00
text_pos                 0.000000e+00
text_compound           -9.638000e-01
hashtags_neg             0.000000e+00
hashtags_neu             0.000000e+00
hashtags_pos             0.000000e+00
hashtags_compound       -2.500000e-01
hour                     0.000000e+00
delta_time               2.125083e-08
log10_delta_time         0.000000e+00
dcompound_dTime         -8.500167e-01
dcompound_dTweet        -9.915572e-01
integral_compound_5     -7.674317e-01
integral_compound_10    -4.129777e-01
delta_compound_mean     -1.000000e+00
delta_compound_median   -9.847757e-01
dtype: float64

In [202]:
rescale_df.to_csv('./tweet_data/scaled_tweet_features.csv')
np.save('./tweet_data/zero_to_one_scaling.npy',np.array(scale1))
np.save('./tweet_data/negone_to_one_scaling.npy',np.array(scale2))

In [3]:
anomalies_df = pd.read_csv(\
            '../data/processed/anomalyandstock_tagged_tweet_features.csv')\
            .drop('Unnamed: 0',axis='columns')

In [5]:
anomalies_df.columns

Index(['username', 'tweet_id', 'reply_to', 'retweets', 'favorites', 'hashtags',
       'mentions', 'text', 'permalink', 'Time', 'hashtags_token',
       'mentions_token', 'reply_to_token', 'text_neg', 'text_neu', 'text_pos',
       'text_compound', 'hashtags_neg', 'hashtags_neu', 'hashtags_pos',
       'hashtags_compound', 'hour', 'delta_time', 'log10_delta_time',
       'dcompound_dTime', 'dcompound_dTweet', 'integral_compound_5',
       'integral_compound_10', 'delta_compound_mean', 'delta_compound_median',
       'anomalous', 'stock_time', 'stock_price'],
      dtype='object')

In [7]:
anomalies_df[['text']].head

<bound method NDFrame.head of                                                    text
0     please ignore prior tweets, as that was someon...
1     went to iceland on sat to ride bumper cars on ...
2     i made the volume on the model s  go to 11  no...
3     great voltaire quote, arguably better than twa...
4                     that was a total non sequitur btw
...                                                 ...
9703  congratulations bob   doug on docking   hatch ...
9704         ,    ,                                 ...
9705  brought home by same person who placed it ther...
9706                 must be due to relativistic aging
9707                                   nine years later

[9708 rows x 1 columns]>

In [ ]:
elon_df = pd.read_csv('../data/raw/elonmusk.csv')\
                        .drop('Unnamed: 0',axis='columns')